package com.suma.dao;

import org.apache.ibatis.annotations.Param;

import java.util.List;


public interface BaseDAO<T, Ex, PK> {

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Wed Nov 15 09:45:32 CST 2017
     */
    long countByExample(Ex example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Wed Nov 15 09:45:32 CST 2017
     */
    int deleteByExample(Ex example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Wed Nov 15 09:45:32 CST 2017
     */
    int deleteByPrimaryKey(PK pk);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Wed Nov 15 09:45:32 CST 2017
     */
    int insert(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Wed Nov 15 09:45:32 CST 2017
     */
    int insertSelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Wed Nov 15 09:45:32 CST 2017
     */
    List<T> selectByExample(Ex example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Wed Nov 15 09:45:32 CST 2017
     */
    T selectByPrimaryKey(PK pk);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Wed Nov 15 09:45:32 CST 2017
     */
    int updateByExampleSelective(@Param("record") T record, @Param("example") Ex example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Wed Nov 15 09:45:32 CST 2017
     */
    int updateByExample(@Param("record") T record, @Param("example") Ex example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Wed Nov 15 09:45:32 CST 2017
     */
    int updateByPrimaryKeySelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated Wed Nov 15 09:45:32 CST 2017
     */
    int updateByPrimaryKey(T record);
}
